#!/bin/bash 

# Redirect output to log file
rm build.log
exec > >(tee -i build.log)
exec 2>&1

CERT=deepin-uefi-ca.der
SBAT=sbat.deepin.csv
OUTNAME=shimx64
SHIM_DBX=shim.dbx

rm -rf shim
rm BOOTX64.EFI
rm $OUTNAME.efi
rm $OUTNAME.cab
rm $OUTNAME.cksum



# Get shim from a tar file
RELEASEPATH="https://github.com.cnpmjs.org/rhboot/shim/releases/download/15.4/shim-15.4.tar.bz2"
curl -L $RELEASEPATH | tar -xj || exit 1
#tar -xjf shim.tar.bz2
mv shim-15.4 shim


# Get shim from a repository
BRANCH=shim-15.4
REPOSITORY="https://github.com.cnpmjs.org/rhboot/shim.git"
#git clone --recursive -b $BRANCH $REPOSITORY shim


cp $CERT shim/
cp $SBAT shim/data/
cp $SHIM_DBX shim/

cd shim
export VENDOR_CERT_FILE=$CERT
#export VENDOR_DBX_FILE=$SHIM_DBX
export DEFAULT_LOADER="\\\\\\\\grub.efi"
make

cp shimx64.efi ../$OUTNAME.efi
cd ..

sha256sum -b $OUTNAME.efi > $OUTNAME.cksum

cp $OUTNAME.efi BOOTX64.EFI
lcab BOOTX64.EFI $OUTNAME.cab
